# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 07:13
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import friendbnb.models


class Migration(migrations.Migration):

    dependencies = [
        ('friendbnb', '0002_auto_20160217_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=True, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text='The author of the review', on_delete=models.SET(friendbnb.models.get_sentinel_user), related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='friendbnb.Listing'),
        ),
    ]
