# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 07:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendbnb', '0003_auto_20160217_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
